### PR TITLE
Update maintainer info

### PR DESCRIPTION
**Pull request by twopoint718**
Just providing new email addresses

### CODE REVIEW

**Comment by twopoint718** [comment]
Please pay attention to me
This PR is cool too, :sunglasses:, @wstrinz

**Comment by wstrinz** [comment]
NB: anyone who wants me to merge PRs would do well to post animal pictures in the comments

**Comment by wstrinz** [comment]
Also I maybe be support contacting you for support requests sometime soon; working on a little Haskell API and oddly you and Jon's blog series is one of the best references I could find

**Comment by twopoint718** [comment]
Awesome, yeah hit me up for Haskell info _anytime_.

**Pull request merged**
